# テスト環境
services:
  java-api:
    build: .
    ports:
      - "8080:8080"

    command: >
      sh -c "
      ./mvnw compile &&
      ./mvnw spring-boot:run -Dspring-boot.run.fork=false
      "

    volumes:
      - ./src:/app/src

    environment:
      SPRING_PROFILES_ACTIVE: test
      SPRING_APPLICATION_NAME: growth_record_java
      JAVA_TOOL_OPTIONS: >
        -Dspring.jpa.show-sql=true
        -Dlogging.level.root=DEBUG
        -Dspring.devtools.restart.enabled=true

    tty: true
