spring.application.name=growth_record_java
debug=true
spring.devtools.restart.enabled=true
spring.devtools.restart.poll-interval=1000
spring.devtools.restart.quiet-period=400
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
